export { default as Home } from './Home/Home'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as CreateVideo } from './CreateVideo/CreateVideo'
export { default as DetailVideo } from './DetailVideo/DetailVideo'
export { default as Creators } from './Creators/Creators'
export { default as DetailCreator } from './DetailCreator/DetailCreator'
